insert into profiles (display_name, bio, creator_rating) values
('Copenhagen Suborbitals', 'Volunteer-built amateur spaceflight program with public rocket and mission documentation.', 4.9),
('Delft Aerospace Rocket Engineering', 'Student rocketry society building high-altitude sounding rockets.', 4.8),
('HyEnD Stuttgart', 'Student hybrid-engine development team with public flight archives.', 4.7),
('USC Rocket Propulsion Laboratory', 'Student-run advanced rocketry laboratory focused on student-built launch vehicles.', 4.9),
('Princeton Rocketry Club', 'University rocketry team pursuing high-altitude student launch vehicles.', 4.6),
('Space Concordia Rocketry Division', 'Student aerospace team building competition and research rockets.', 4.6),
('BPS.space', 'Independent maker project exploring active guidance and reusable model rockets.', 4.9),
('UCI Rocket Project', 'Student team developing liquid propulsion test vehicles and launch systems.', 4.6),
('Boston University Rocket Propulsion Group', 'Student research group pursuing high-altitude rocketry.', 4.6);

insert into projects
(slug, title, description, price_cents, difficulty, motor_class, predicted_altitude_m, actual_altitude_m, verification_status, tags, has_web_cad, has_flight_log, has_telemetry, has_thrust_data, has_stl_step, verified_flight, fork_count, download_count, royalty_percent, public_reference_name, public_reference_url)
values
('copenhagen-spica-reference', 'Copenhagen Suborbitals Spica Reference', 'Public amateur-spaceflight reference project structured for CAD, simulation, evidence review, and safe project comparison.', 0, 'High Power', 'Liquid bipropellant', 105000, null, 'Design reviewed', array['amateur spaceflight','crew capsule','liquid engine'], true, true, false, true, true, false, 428, 12400, 2, 'Copenhagen Suborbitals Spica project', 'https://copenhagensuborbitals.com/rockets-2/spica'),
('copenhagen-nexo-ii-reference', 'Copenhagen Suborbitals Nexo II Flight Archive', 'Public amateur liquid-rocket mission archive with telemetry-oriented project structure and evidence notes.', 1800, 'High Power', 'Liquid bipropellant', 8500, 6500, 'Telemetry attached', array['sea launch','guidance test','amateur liquid'], true, true, true, true, false, false, 302, 9300, 2, 'Copenhagen Suborbitals Nexo II mission', 'https://copenhagensuborbitals.com/missions/nexo-ii/'),
('dare-stratos-iv-reference', 'DARE Stratos IV Student Sounding Rocket', 'Student sounding-rocket reference project for high-altitude CAD, systems integration, and simulation comparison.', 2400, 'High Power', 'Hybrid sounding rocket', 100000, null, 'Design reviewed', array['student team','hybrid motor','sounding rocket'], true, false, false, true, true, false, 365, 10100, 2, 'DARE Stratos IV project', 'https://dare.tudelft.nl/stratos4/'),
('hyend-heros-3-reference', 'HyEnD HEROS 3 Hybrid Rocket', 'Hybrid student rocket archive with flight evidence, recovery layout, and telemetry workspace for high-altitude analysis.', 1600, 'High Power', 'Hybrid', 32000, 30000, 'Telemetry attached', array['student team','hybrid','altitude record'], true, true, true, true, false, false, 224, 6800, 2, 'HyEnD HEROS project archive', 'https://hyend.de/index.php/previous-projects/heros/'),
('usc-rpl-aftershock-ii-reference', 'USC RPL Aftershock II Flight Record', 'Student-built high-altitude flight record organized as a project repository with media proof and analysis placeholders.', 3200, 'High Power', 'Student-built solid', 144000, 143300, 'Media proof', array['student-built motor','altitude record','flight archive'], true, true, false, true, true, false, 512, 15600, 2, 'USC RPL Aftershock II project', 'https://www.uscrpl.com/aftershock-ii'),
('princeton-spaceshot-reference', 'Princeton Rocketry SpaceShot Airframe', 'Student space-shot airframe reference for carbon structure, recovery, avionics, and high-altitude documentation workflows.', 1200, 'High Power', 'Solid sounding rocket', 91440, null, 'Design reviewed', array['student team','space shot','carbon airframe'], true, false, false, false, true, false, 188, 4200, 2, 'Princeton Rocketry SpaceShot 2018-19', 'https://www.princetonrocketry.com/spaceshot-2018-19'),
('space-concordia-starsailor-reference', 'Space Concordia Starsailor Reference', 'Competition and research rocket reference project organized around public team documentation and systems integration.', 1500, 'High Power', 'Competition sounding rocket', 30480, null, 'Design reviewed', array['student team','Spaceport America Cup','systems integration'], true, false, false, false, true, false, 176, 3900, 2, 'Space Concordia Rocketry projects', 'https://spaceconcordia.ca/rocketry'),
('bps-scout-f-reference', 'BPS.space Scout F Thrust-Vector Testbed', 'Independent maker rocket project with active-guidance media proof and flight-computer style documentation.', 900, 'Advanced', 'Model rocket motor', 300, 290, 'Media proof', array['individual maker','thrust vector control','active guidance'], true, true, false, false, false, false, 694, 20800, 2, 'BPS.space public project overview', 'https://bps.space/pages/about'),
('uci-rocket-blue-v2-reference', 'UCI Rocket Project Rocket Blue V2', 'Student liquid test-vehicle reference project with static-fire evidence workflow and launch-vehicle CAD organization.', 1100, 'High Power', 'Liquid test vehicle', 3000, null, 'Static fire data', array['student team','liquid engine','test vehicle'], true, true, true, true, true, false, 142, 3100, 2, 'UCI Rocket Project liquids program', 'https://www.rocket.eng.uci.edu/liquids-2/'),
('burpg-spaceshot-reference', 'BURPG Space-Shot Development Archive', 'Student research archive for high-altitude rocketry, project evidence, recovery planning, and analysis comparison.', 0, 'High Power', 'Student research rocket', 100000, null, 'Design reviewed', array['student team','space-shot','research archive'], true, false, false, true, true, false, 231, 5700, 2, 'BURPG public project site', 'https://burpg.org/');
